### ISSUE TITLE
Getting following error with local-npm server but when it reset my npm registery to 'npm set registry https://registry.npmjs.org/' every thing works fine.

### ISSUE THREAD

**Issue by rameshbansal** [juliangruber/npm-local#4]
![image](https://user-images.githubusercontent.com/11285768/33760554-080d0404-dc2c-11e7-8625-a30e09edd576.png)

**Comment by juliangruber** [comment]
This module isn't about local npm servers, it's for downloading all that npm has. You probably want to create this issue in another repo, either the npm/yarn client or the private npm server.
